### ISSUE TITLE
Exporting bookmarks

### ISSUE THREAD

**Issue by levidurfee** [phparsenal/fast-forward#13]
Will need an extra field in the database so you can flag bookmarks as 'shareable'.

**Comment by nochso** [comment]
* [ ] Add command `export`
* [ ] Add command `import` or maybe only parameter on `export`
* [ ] Add Bookmark column `shareable`
* [ ] Add default setting `ff.shareable 0` which is used when adding new bookmarks
* [ ] Update readme
