### ISSUE TITLE
Deciding on a workflow

### ISSUE THREAD

**Issue by nochso** [phparsenal/fast-forward#3]
I think [Gitflow](https://de.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) has been mentioned. I have no experience with it and seems a bit involved.

Maybe two branches:
- master: Gets tagged with stable releases
- develop: Anything new gets developed here

Where would hotfixes go? Directly to master or develop first?

Or just keep everything on master as it is and only tag stable releases. Easiest if we don't get busy.

**Comment by Hipp04** [comment]
I'd suggest new features get developed on their own branches and then merged into develop when they're complete enough to be more widely used/tested. That way we can encourage work on new features while still maintaining a clean development branch.

**Comment by samayo** [comment]
@Hipp04 suggestion seems good for me.

**Comment by teklifeinfo** [comment]
:+1:

**Comment by nochso** [comment]
Ok. Master, develop and feature branches it is!
