### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by nochso** [phparsenal/fast-forward#9]
## Initial idea
What do you think about storing user settings in the SQLite database?
I imagine this is important as everyone has different preferences and habits :)
Some examples:

* `ff set maxrows 5` limit results to 5 rows
* `ff set sort hitcount` sort results by hit count
* `ff set sort` display help and possible values
* `ff set interactive 0` never ask for parameters interactively
* `ff unset interactive` could do the same as setting 0?
* `ff export` something like this to let you take your settings with you

About exporting:
This could output all settings as a list of `set` commands that you can run on another system. Or just a simple `key value` text file you can import.
Exporting the bookmarks would be nice too, however there should be a way to be selective? Maybe differentiate between "shareable" and "local" bookmarks?

Table with two rows for key and value?

-------
## To do / Tasks
* [x] Add table and model class
* [x] Basic functionality to set and get settings (class Client)
  * `ff set [key] [value]`
* [x] Output quoted list of known settings: `-l --list`
* [x] Import from same list (via input file and/or pipe)
  * Import settings from previous `ff set -l > file.txt`  
      `ff set -i file.txt`
  * Import setting via piping  
      `cat file.txt | ff set`
* [x] Various settings
  * [x] `ff set maxrows 5` limit results to 5 rows
  * [x] `ff set sort hitcount` sort results by hit count (default)
  * [x] `ff set sort` display help and possible values
  * [x] `ff set interactive 0` never ask for parameters interactively (default 1)
  * [x] `ff set color 0` disable colors (default 1)
* [x] Possibly namespace/prefix names: built-in `ff.maxrows`, external plugin `rssalert.timer` and everything else for user defined `foobar`
* [x] Allow using these variables in commands. What's a good identifier that won't clash with win cli and bash? maybe `cd @foobar` or `cd :foobar:`

**Comment by levidurfee** [comment]
This seems like two questions combined into one.

I'm good with using SQLite for the user's settings.

## settings

I think it would be handy to export as `key`  `value` to a text file, that you could import on another machine. Including the `set` command might make it more complicated to import on different systems. I think it would be easier to just write code to import the file with `key`  `value` into the SQLite db.

I think a table with 2 columns would be fine

| key          | value |
| :----------- | :---- |
| maxrows      | 5     |
| interactive  | 0     |

## exporting bookmarks

I like the idea of exporting bookmarks. We can add another column to flag the bookmark as 'shareable'.

Let me know if I don't make any sense :)

**Comment by nochso** [comment]
Yep, makes sense and I agree. Wanna open the issue for exporting bookmarks?

**Comment by levidurfee** [comment]
Sure. I'm going to be free this weekend to work on this project. I'll hopefully meet you on gitter.

**Comment by nochso** [comment]
Great. I'm on vacation after tomorrow so I'll probably be more active and less active should I travel :)
